// Sources/Engine/Assignment.swift
// Orientation-aware template default + brute-force content-fit slot assignment.
// Pure Foundation - no SwiftUI/UIKit/Photos/Vision imports.
import Foundation
#if canImport(CoreGraphics)
import CoreGraphics
#endif

// MARK: - Default template index

/// Picks a sensible starting template out of `templates(for:)`'s list for the
/// given photo orientations (one CGSize per photo, in the same order the
/// photos will be passed to `templates(for:)`).
///
/// Index mapping (mirrors `templates(for:)`'s fixed order):
///   - 4 photos: always index 0 (2x2 columns-first) - orientation-agnostic.
///   - 2 photos: index 0 = side-by-side ("columns" - two portrait/square
///     photos read best side by side), index 1 = stacked ("rows" - two
///     landscape photos read best stacked).
///   - 3 photos: index 0 = 3 columns, index 1 = 3 rows, same rationale.
/// Majority orientation decides: a photo is "portrait-or-square" when
/// width <= height, "landscape" otherwise. Ties (equal counts, only
/// possible with 2 photos split 1-1) default to the columns variant (index 0).
func defaultTemplateIndex(orientations: [CGSize]) -> Int {
    if orientations.count == 4 { return 0 }

    var portraitOrSquareCount = 0
    var landscapeCount = 0
    for size in orientations {
        if size.width <= size.height {
            portraitOrSquareCount += 1
        } else {
            landscapeCount += 1
        }
    }

    // Majority landscape -> the "rows" variant (index 1); everything else
    // (majority portrait/square, or a tie) -> the "columns" variant (index 0).
    return landscapeCount > portraitOrSquareCount ? 1 : 0
}

// MARK: - Content-fit slot assignment

/// Rebuilds `node`'s tree, replacing each leaf (in traversal order) with the
/// corresponding entry of `ids`. `ids.count` must equal the leaf count.
private func replacingLeavesInOrder(_ node: Node, with ids: [PhotoID], cursor: inout Int) -> Node {
    switch node {
    case .leaf:
        let id = ids[cursor]
        cursor += 1
        return .leaf(id)
    case .split(let axis, let fractions, let children):
        return .split(axis: axis, fractions: fractions, children: children.map { replacingLeavesInOrder($0, with: ids, cursor: &cursor) })
    }
}

/// All permutations of `array`, in a stable, deterministic order: the
/// identity permutation (elements in their original order) is always first,
/// and every subsequent permutation is generated by always trying the
/// lowest-remaining-index element next. This is what makes "ties broken by
/// input order" well-defined - the first minimal-cost permutation found in
/// this enumeration is the one whose slot assignment is closest to the
/// original ordering.
private func permutations<T>(_ array: [T]) -> [[T]] {
    guard array.count > 1 else { return [array] }
    var result: [[T]] = []
    for i in 0..<array.count {
        var rest = array
        let picked = rest.remove(at: i)
        for tail in permutations(rest) {
            result.append([picked] + tail)
        }
    }
    return result
}

private func aspect(_ size: CGSize) -> Double {
    guard size.height > 0 else { return 1 }
    return Double(size.width) / Double(size.height)
}

private func aspect(_ rect: CGRect) -> Double {
    guard rect.height > 0 else { return 1 }
    return Double(rect.width) / Double(rect.height)
}

/// Brute-forces every permutation (at most 4! == 24) of `photoSizes`'s photos
/// into `template`'s leaf slots and returns the template with leaves
/// reassigned to whichever permutation minimizes
/// `sum_over_slots |log(photoAspect) - log(cellAspect)|`
/// (cell rects come from solving `template` at `canvasSize`/`border`). Ties -
/// including the trivial "no reassignment needed" case - are broken in favor
/// of the permutation closest to the template's original leaf order (see
/// `permutations` above).
func contentFitAssignment(
    photoSizes: [PhotoID: CGSize],
    template: Node,
    canvasSize: CGSize,
    border: BorderStyle
) -> Node {
    let originalOrder = photoIDs(in: template)
    guard originalOrder.count > 1 else { return template }

    let (cells, _) = solve(root: template, canvasSize: canvasSize, border: border)
    let cellByID = Dictionary(uniqueKeysWithValues: cells.map { ($0.id, $0.rect) })

    // Slot rects in the SAME order as `originalOrder`.
    let slotRects: [CGRect] = originalOrder.map { cellByID[$0] ?? .zero }
    let slotAspects: [Double] = slotRects.map { aspect($0) }
    let photoAspects: [Double] = originalOrder.map { id in
        aspect(photoSizes[id] ?? CGSize(width: 1, height: 1))
    }

    var bestCost = Double.infinity
    var bestPermutation = originalOrder

    for perm in permutations(originalOrder) {
        var cost: Double = 0
        for slot in 0..<perm.count {
            guard let photoIndex = originalOrder.firstIndex(of: perm[slot]) else { continue }
            let photoAspect = photoAspects[photoIndex]
            let cellAspect = slotAspects[slot]
            guard photoAspect > 0, cellAspect > 0 else { continue }
            cost += abs(log(photoAspect) - log(cellAspect))
        }
        if cost < bestCost {
            bestCost = cost
            bestPermutation = perm
        }
    }

    var cursor = 0
    return replacingLeavesInOrder(template, with: bestPermutation, cursor: &cursor)
}
